[package]
name = "wattwolf"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["producer_consumer_swapped"]
producer_consumer_swapped = []


[dependencies]
serde = { version = "1.0", features = ["derive"] }
serialport = "4.8.1"
sml-rs = "0.4.0"
thiserror = "2.0.18"
toml = "0.8.23"
phf = { version = "0.13.1", features = ["macros"] }