name: test
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - run: |
          sudo apt-get install --assume-yes libudev-dev

      - run: cargo fmt --check
      - run: cargo check --all-targets
      - name: Run Tests
        run: cargo nextest run

      - uses: crusty-pie/clippy@v1
        with:
          args: --all-features --all-targets -- -D clippy::pedantic
